import { useMemo } from 'react'

import { REFERENCES, DATA_SOURCES } from './bibliography'
import { countDistinctPermutations, internalOf } from '../reading/permutations'
import type { ScrambleEngine, TransformSettings } from '../reading/transform'
import { Scrambled } from '../components/Scrambled'

/**
 * The rabbit hole underneath the toy.
 *
 * The demonstrations here are generated by the same engine the reader has been
 * playing with, so the essay cannot drift out of sync with what the site actually
 * does. Where a claim comes from a study it names the study.
 */

const BY_ID = new Map(REFERENCES.map((r) => [r.id, r]))

function Cite({ id, children }: { id: string; children: React.ReactNode }) {
  const ref = BY_ID.get(id)
  if (!ref) return <>{children}</>
  return (
    <a href={ref.url} target="_blank" rel="noreferrer noopener" title={`${ref.title} — ${ref.venue}`}>
      {children}
    </a>
  )
}

interface ExplainerProps {
  engine: ScrambleEngine
  settings: TransformSettings
}

/** One word, several of its legal rearrangements, ordered by our own score. */
function Ladder({
  word,
  engine,
  settings,
}: {
  word: string
  engine: ScrambleEngine
  settings: TransformSettings
}) {
  const rows = useMemo(() => {
    const candidates = engine.candidatesFor(word, { ...settings, difficulty: 50 })
    if (candidates.length === 0) return []
    const picks = [0, 0.25, 0.5, 0.75, 1].map((q) =>
      candidates[Math.round(q * (candidates.length - 1))],
    )
    // Deduplicate in case the word has very few legal rearrangements.
    const seen = new Set<string>()
    return picks.filter((c) => !seen.has(c.permutation) && seen.add(c.permutation))
    // cacheVersion changes when the word list lands; see Scrambled.tsx.
    // oxlint-disable-next-line react-hooks/exhaustive-deps
  }, [word, engine, engine.cacheVersion, settings])

  const total = countDistinctPermutations(internalOf(word)) - 1

  return (
    <div className="demo">
      <p className="demo__title">
        {word} · {total.toLocaleString()} legal rearrangements
      </p>
      <p className="demo__legend">
        Five of them, easiest first. The meter is our scramble score: how much we
        predict each one slows you down.
      </p>
      <div className="ladder">
        {rows.map((row) => (
          <div className="ladder__row" key={row.permutation}>
            <span className="ladder__word">{row.permutation}</span>
            <span className="ladder__meter">
              <i style={{ width: `${row.breakdown.score}%` }} />
            </span>
            <span className="ladder__score">{row.breakdown.score}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

/**
 * Transposed-letter neighbours that our rule can actually reach. Each of these is
 * a pair of real words that differ only in the order of their internal letters,
 * so one is a legal rearrangement of the other.
 */
const NEIGHBOUR_PAIRS: Array<[string, string, string]> = [
  ['clam', 'calm', 'calm is about 50x commoner'],
  ['form', 'from', 'from is about 40x commoner, and a function word'],
  ['sacred', 'scared', 'scared is about 8x commoner'],
  ['trail', 'trial', 'within a factor of three of each other'],
  ['tired', 'tried', 'both extremely common, so neither wins easily'],
  ['martial', 'marital', 'martial is about 5x commoner'],
]

export function Explainer({ engine, settings }: ExplainerProps) {
  const heading = (text: string) => (
    <Scrambled as="h2" text={text} engine={engine} settings={settings} />
  )

  return (
    <div className="essay shell">
      {heading('Wait, why can I read this?')}

      <p className="lede">
        Because reading was never letter-by-letter decoding in the first place. Your eyes
        deliver a smear of partial evidence and the rest of you reconstructs a sentence from
        it. Rearranging the middle of a word damages some of that evidence, but rarely all
        of it.
      </p>

      <p>
        The internet version of this claim arrived in 2003 as a paragraph about a study at
        Cambridge University. There was no such study.{' '}
        <Cite id="davis">Matt Davis</Cite>, at the MRC Cognition and Brain Sciences Unit in
        Cambridge, traced the underlying demonstration to{' '}
        <Cite id="rawlinson">Graham Rawlinson's 1976 PhD thesis</Cite> at Nottingham and wrote
        the definitive correction, which is still the best page on the subject.
      </p>

      <p>
        The meme's stronger claim — that letter order simply does not matter — is false.
        When{' '}
        <Cite id="rayner2006">Rayner, White, Johnson and Liversedge (2006)</Cite> recorded eye
        movements instead of asking people whether they could cope, jumbled text was read
        reliably more slowly.
        You can read it. You are also paying for it.
      </p>

      <p>
        The paragraph that convinced everyone was also unusually kind. Davis points out that
        its short words and function words were untouched, its transpositions were mostly
        between neighbouring letters, and — crucially — none of its rearrangements
        accidentally produced a different English word.
      </p>

      {heading('Letter position is soft, not absent')}

      <p>
        The evidence for softness is strong. Show someone <em>jugde</em> too quickly to
        consciously register, and it primes <em>COURT</em> almost as well as the word{' '}
        <em>judge</em> does (<Cite id="perea2003">Perea &amp; Lupker, 2003</Cite>). It still works when the swapped
        letters are not next to each other: <em>caniso</em> reaches <em>CASINO</em> (Perea
        &amp; Lupker, 2004).
      </p>

      <p>
        But softness is not indifference, and it is not uniform across the word. White,
        Johnson, Liversedge and Rayner (2008) found that transposing letters near the{' '}
        <em>beginning</em> of a word disrupted reading far more than the same transposition
        near the end — sentence reading time rose about 36% for the worst case against about
        11% for the mildest. Low-frequency words suffered more than common ones.
      </p>

      <p>
        There is a consonant-and-vowel asymmetry too. Lupker, Perea and Davis (2008) found a
        healthy priming effect when two consonants swapped and essentially none when two
        vowels did. Moving the vowels seems to damage word identity in a way that moving the
        consonants does not.
      </p>

      {heading('Not all scrambles are equal')}

      <p>
        This is the actual point of the site. Under the first-and-last-letter rule, every
        arrangement below carries exactly the same information: same letters, same first
        letter, same last letter, same length. By the meme's logic they should be equally
        readable.
      </p>

      <Ladder word="practical" engine={engine} settings={settings} />
      <Ladder word="important" engine={engine} settings={settings} />

      <p>
        Read down either list. If the bottom line costs you more than the top one, the score
        is tracking something real. That order is a prediction, and you are the test of it.
      </p>

      <p>
        You can check any word this way, not just these two. Click a rearranged word in the
        text at the top of the page and a panel opens with the measurements behind its score:
        how far each letter travelled, how many of the original letter pairs survived, and
        whether the result happens to spell another English word.
      </p>

      <p>
        Notice also how fast the space grows. A four-letter word has a single legal
        rearrangement — <em>word</em> can only ever become <em>wrod</em>. A nine-letter word
        has tens of thousands. That asymmetry is most of why the original meme reads so
        easily: it is mostly made of words with nowhere to go.
      </p>

      {heading('The interesting failure: when a scramble is another word')}

      <p>
        Most rearrangements produce nonsense, and nonsense is merely slow. The genuinely
        nasty case is when the rearrangement lands on a different real word, because then
        your reading machinery has a confident wrong answer available.
      </p>

      <div className="demo">
        <p className="demo__title">Pairs our rule can actually reach</p>
        <div className="pairs">
          {NEIGHBOUR_PAIRS.map(([a, b, gloss]) => (
            <div className="pair" key={a}>
              <span>{a}</span>
              <span className="pair__arrow">⇄</span>
              <span>{b}</span>
              <span className="pair__gloss">{gloss}</span>
            </div>
          ))}
        </div>
      </div>

      <p>
        These are called{' '}
        <a
          href="https://en.wikipedia.org/wiki/Transposed_letter_effect"
          target="_blank"
          rel="noreferrer noopener"
        >
          transposed-letter neighbours
        </a>
        , and they cost something real. Acha and
        Perea (2008) found that a word with a higher-frequency transposed-letter neighbour is
        read more slowly in ordinary sentences; Pagán, Paterson, Blythe and Liversedge (2016)
        replicated it in eye movements. Johnson, Staub and Fleri (2012) showed the cost lives
        almost entirely in the slow tail of responses — most words still just pop, and
        occasionally one catches. Johnson, Koch and Wootten (2024) went further and found
        readers sometimes simply report the wrong one of the pair.
      </p>

      <p>
        A note on a famous example: <em>angel</em> and <em>angle</em> are the pair everyone
        reaches for, but our rule cannot produce it. They differ in their final letter, and we
        never move the first or last letter. It is a transposed-letter neighbour and it is
        outside the space this site explores.
      </p>

      <p>
        This is what the <strong>Adversarial</strong> setting searches for — it is under
        &ldquo;Choosing by&rdquo;, below the text. It is the only part of our scoring with a
        real prediction attached: the algorithm is claiming that this particular arrangement
        will interfere with you, and it can be wrong in a way you can feel. The{' '}
        <strong>Random (control)</strong> setting beside it does no scoring at all, which is
        the comparison worth making: if the two feel the same to you, our scoring is not
        earning its place.
      </p>

      {heading('Context is doing error correction')}

      <p>
        A scrambled word in isolation and the same word in a sentence are not the same task.
        Luke and Christianson (2012) found that when a sentence makes a word highly
        predictable, the transposed-letter cost disappears entirely.
      </p>

      <div className="demo">
        <p className="demo__title">The same word, three amounts of help</p>
        <div className="context-demo">
          <p className="context-demo__case">
            <span className="context-demo__tag">Alone</span>
            <span className="scrambled-inline">pcatircal</span>
          </p>
          <p className="context-demo__case">
            <span className="context-demo__tag">Unhelpful sentence</span>
            She mentioned it was <span className="scrambled-inline">pcatircal</span>, which
            surprised nobody.
          </p>
          <p className="context-demo__case">
            <span className="context-demo__tag">Helpful sentence</span>
            Forget the theory for a moment and give me a{' '}
            <span className="scrambled-inline">pcatircal</span> suggestion I can act on today.
          </p>
        </div>
      </div>

      <p>
        Human reading is not character recognition. It is uncertain visual evidence combined
        with an enormous amount of learned structure about which words exist, which words
        follow which, and what the sentence is probably about.
      </p>

      {heading('An experiment hiding inside a toy')}

      <p>
        The question we actually want answered is narrow enough to be tractable:
      </p>

      <p className="lede">
        Given the same word, with the same first and last letters and exactly the same
        internal letters, which arrangements are easiest and hardest for people to recognise?
      </p>

      <p>
        The permutation constraint makes an unusually clean laboratory. Information content,
        word length, whitespace, sentence and meaning are all held fixed. Only character order
        varies. Plausible predictors include character displacement, surviving letter
        sequences, orthographic neighbourhood, word frequency, morphology, pronounceability
        and sentence predictability — and this site currently measures the first few of those.
      </p>

      <p>
        Then the sharper version: can we search the legal rearrangements of a word for the one
        specifically optimised to interfere with human recognition? That is what Adversarial
        attempts, and we do not yet know how well it works.
      </p>

      <h3>What this site does not know</h3>

      <p>
        The scramble score is a hand-tuned weighted average of the features listed in the word
        inspector. The features are motivated by the studies cited below. The weights are
        guesses. Nobody's reading times have been fitted to them, no study cited here tested
        arbitrary rearrangements of the kind we generate, and none of them tested our scoring.
      </p>

      <p>
        That is deliberately why the number is called a <em>scramble score</em> and not a
        predicted reading difficulty. If it ever earns the second name, it will be because
        someone measured people rather than because we adjusted the weights until the output
        matched our intuitions.
      </p>

      <p>
        We are also not making any claim about dyslexia, about reading ability, or about what
        your performance here says about you. Those comparisons need careful experimental and
        ethical design that a web toy does not have.
      </p>

      {heading('Sources')}

      <p>
        Every entry was checked against the publisher's record while this site was built.
        Where a claim above rests on one of these, the note says what we take from it.
      </p>

      <ul className="refs">
        {REFERENCES.map((ref) => (
          <li className="ref" key={ref.id}>
            <span className="ref__cite">
              {ref.authors} ({ref.year}).{' '}
              <a href={ref.url} target="_blank" rel="noreferrer noopener">
                {ref.title}
              </a>
              . <em>{ref.venue}</em>.
            </span>
            <div className="ref__note">{ref.relevance}</div>
          </li>
        ))}
      </ul>

      <h3>Data</h3>
      <ul className="refs">
        {DATA_SOURCES.map((source) => (
          <li className="ref" key={source.label}>
            <span className="ref__cite">
              <a href={source.url} target="_blank" rel="noreferrer noopener">
                {source.label}
              </a>
            </span>
            <div className="ref__note">{source.detail}</div>
          </li>
        ))}
      </ul>

      <div className="colophon">
        <p>
          <strong>hradtoraed.com</strong> — the name obeys the rule it investigates.{' '}
          <em>hard</em> → <em>hrad</em> and <em>read</em> → <em>raed</em> both keep their first
          and last letters.
        </p>
        <p>
          Everything on this page runs in your browser. Nothing you paste is uploaded, logged
          or stored anywhere, and the URL never contains your text. You do not have to take
          that on faith —{' '}
          <a
            href="https://github.com/rjwalters/hradtoraed"
            target="_blank"
            rel="noreferrer noopener"
          >
            the source is on GitHub
          </a>
          , including the scoring function, so you can check both the privacy claim and the
          arithmetic behind every number on this page.
        </p>
      </div>
    </div>
  )
}
